"""
routers.py
==========
Campayn AI Assistant — FastAPI Route Handlers

All API endpoints in one file for clarity.
In production you'd split these into api/routers/brand.py,
api/routers/creator.py etc. — matching the project structure.

ENDPOINTS
----------
POST /brand/chat      — brand-side assistant
POST /creator/chat    — creator-side assistant
POST /feedback        — log thumbs up/down to LangSmith
GET  /health          — health check + module status
GET  /docs            — auto-generated by FastAPI (Swagger UI)

Author : Mohit Chauhan — Campayn Multimodal AI Assistant
"""

from __future__ import annotations

import time
import uuid

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse

from api.schemas import (
    ChatRequest, ChatResponse, FeedbackRequest,
    FeedbackResponse, HealthResponse, MCQQuestion, PipelineMetrics,
)

# ─────────────────────────────────────────────────────────────────
# ROUTER INSTANCES
# Each router groups related endpoints under a URL prefix
# ─────────────────────────────────────────────────────────────────

brand_router    = APIRouter(prefix="/brand",    tags=["Brand"])
creator_router  = APIRouter(prefix="/creator",  tags=["Creator"])
health_router   = APIRouter(prefix="",          tags=["System"])
feedback_router = APIRouter(prefix="/feedback", tags=["Feedback"])


# ─────────────────────────────────────────────────────────────────
# SHARED HELPER — run the pipeline and build the response
# Both /brand/chat and /creator/chat use this same logic.
# The only difference is the role passed in.
# ─────────────────────────────────────────────────────────────────

async def _run_chat(request: ChatRequest, role: str) -> ChatResponse:
    """
    Core handler used by both brand and creator endpoints.

    Flow:
      1. Generate session_id if not provided
      2. Call run_pipeline() from graph.py
      3. Compute metrics
      4. Return structured ChatResponse
    """
    from api.graph                       import run_pipeline
    from api.observability.langsmith_setup import compute_pipeline_metrics, build_run_metadata

    # Generate session ID on first message
    session_id = request.session_id or str(uuid.uuid4())

    try:
        # ── Run the full LangGraph pipeline ──────────────────────────────
        result = run_pipeline(
            query       = request.query,
            role        = role,
            session_id  = session_id,
            image_b64   = request.image_b64,
            mcq_answers = request.mcq_answers,
        )

        # ── Build metrics ─────────────────────────────────────────────────
        metrics_data = compute_pipeline_metrics(result)
        metrics = PipelineMetrics(**{
            k: v for k, v in metrics_data.items()
            if k in PipelineMetrics.model_fields
        })

        # ── Handle MCQ interrupt ──────────────────────────────────────────
        if result.get("needs_mcq"):
            raw_questions = result.get("mcq_questions") or []
            mcq_questions = [
                MCQQuestion(
                    field   = q.get("field", ""),
                    label   = q.get("label", ""),
                    options = q.get("options", []),
                    hint    = q.get("hint", ""),
                )
                for q in raw_questions
            ]
            return ChatResponse(
                response      = result.get("response", ""),
                session_id    = session_id,
                role          = role,
                needs_mcq     = True,
                mcq_questions = mcq_questions,
                metrics       = metrics,
            )

        # ── Normal response ───────────────────────────────────────────────
        meta = result.get("metadata", {})
        return ChatResponse(
            response   = result.get("response", ""),
            session_id = session_id,
            role       = role,
            needs_mcq  = False,
            sources    = meta.get("sources", []),
            run_id     = result.get("run_id"),   # LangSmith run ID for feedback
            metrics    = metrics,
        )

    except Exception as e:
        # Return a structured error instead of crashing
        # In production: log to LangSmith + alert
        print(f"[API] Pipeline error (role={role}): {e}")
        raise HTTPException(
            status_code = 500,
            detail      = f"Pipeline error: {str(e)[:200]}",
        )


# ─────────────────────────────────────────────────────────────────
# BRAND ENDPOINTS
# ─────────────────────────────────────────────────────────────────

@brand_router.post(
    "/chat",
    response_model = ChatResponse,
    summary        = "Brand assistant chat",
    description    = (
        "Send a message to the brand-side AI assistant. "
        "The assistant helps with campaign planning, influencer matching, "
        "CPV strategy, brief writing, and campaign diagnostics."
    ),
)
async def brand_chat(request: ChatRequest) -> ChatResponse:
    """
    POST /brand/chat

    Example queries:
      - "Find top fitness micro-influencers for a protein supplement launch"
      - "What CPV should I target for a beauty campaign with ₹2L budget?"
      - "Write a campaign brief for our new skincare line"
    """
    return await _run_chat(request, role="brand")


# ─────────────────────────────────────────────────────────────────
# CREATOR ENDPOINTS
# ─────────────────────────────────────────────────────────────────

@creator_router.post(
    "/chat",
    response_model = ChatResponse,
    summary        = "Creator assistant chat",
    description    = (
        "Send a message to the creator-side AI assistant. "
        "The assistant helps with content improvement, growth strategy, "
        "monetisation advice, and campaign pitching."
    ),
)
async def creator_chat(request: ChatRequest) -> ChatResponse:
    """
    POST /creator/chat

    Example queries:
      - "How do I grow from 10k to 50k followers?"
      - "Review my Reel hook — I'll upload a screenshot"
      - "How do Creator Coins work and when do I get paid?"
    """
    return await _run_chat(request, role="creator")


# ─────────────────────────────────────────────────────────────────
# FEEDBACK ENDPOINT
# Logs user thumbs up/down to LangSmith
# ─────────────────────────────────────────────────────────────────

@feedback_router.post(
    "/",
    response_model = FeedbackResponse,
    summary        = "Log user feedback",
    description    = "Record thumbs up/down on a response. Stored in LangSmith for eval.",
)
async def log_feedback(request: FeedbackRequest) -> FeedbackResponse:
    """
    POST /feedback

    Call this when the user clicks thumbs up or down on a response.
    The run_id comes from the ChatResponse of the rated message.

    Body:
        {"run_id": "abc123", "score": 1.0, "comment": "Very helpful!"}
    """
    from api.observability.langsmith_setup import log_feedback as _log

    success = _log(
        run_id  = request.run_id,
        score   = request.score,
        comment = request.comment or "",
    )

    return FeedbackResponse(
        success = success,
        message = "Feedback logged" if success else "Feedback logging failed (LangSmith may be disabled)",
    )


# ─────────────────────────────────────────────────────────────────
# HEALTH CHECK ENDPOINT
# ─────────────────────────────────────────────────────────────────

@health_router.get(
    "/health",
    response_model = HealthResponse,
    summary        = "Health check",
    description    = "Check API status and module availability.",
)
async def health_check() -> HealthResponse:
    """
    GET /health

    Returns the status of all modules:
      - chromadb: is the vector store loaded?
      - dataframe: are the 56k profiles in memory?
      - langsmith: is tracing enabled?
    """
    import os

    modules = {}

    # Check ChromaDB
    try:
        import chromadb
        persist_dir = os.environ.get("CHROMA_PERSIST_DIR", "data/vector_store")
        client = chromadb.PersistentClient(path=persist_dir)
        col = client.get_collection(
            os.environ.get("CHROMA_COLLECTION_NAME", "campayn_knowledge_base")
        )
        modules["chromadb"] = f"ok ({col.count()} chunks)"
    except Exception as e:
        modules["chromadb"] = f"error: {str(e)[:60]}"

    # Check DataFrame
    try:
        from api.graph import get_dataframe
        df = get_dataframe()
        modules["creator_profiles"] = f"ok ({len(df):,} profiles)"
    except Exception as e:
        modules["creator_profiles"] = f"error: {str(e)[:60]}"

    # Check LangSmith
    langsmith_on = (
        os.environ.get("LANGCHAIN_TRACING_V2", "false").lower() == "true"
        and bool(os.environ.get("LANGCHAIN_API_KEY"))
    )
    modules["langsmith"] = "enabled" if langsmith_on else "disabled"

    # Check Gemini
    gemini_key = os.environ.get("GEMINI_API_KEY", "")
    modules["gemini"] = "configured" if gemini_key else "missing GEMINI_API_KEY"

    # Check Anthropic (automatic fallback if Gemini fails — see api/llm_fallback.py)
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY", "")
    modules["anthropic_fallback"] = "configured" if anthropic_key else "not configured"

    return HealthResponse(
        status       = "ok",
        environment  = os.environ.get("ENVIRONMENT", "development"),
        langsmith_on = langsmith_on,
        modules      = modules,
    )